language: php
php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script: 
  - echo -e "ServerScheme\072 http" >> system/config/config.ini
  - echo -e "ServerName\072 your.domain.name" >> system/config/config.ini
  - php yellow.php version
script: php yellow.php build test
